package brave.springrabbit17;

import brave.spring.rabbit.ITSpringRabbitTracingWithSimpleRabbitListenerContainerFactory;

public class ITSpringRabbit17 extends ITSpringRabbitTracingWithSimpleRabbitListenerContainerFactory {
}